@echo off
echo Starting Makeover Frontend...
cd "c:\Users\dell\Desktop\Makeover-main-1\Makeover-UI-master"
echo Installing dependencies if needed...
call npm install
echo Starting React development server...
call npm start
pause
